apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-server
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec :
      containers:
      - name: web-server
        image: arokiagetz/k8s-web-server:v1