#! /bin/bash

cd "$(dirname "$0")/.."

if [ -z "$1" ]
then
echo "Enter the version number after the script:"
exit
fi

TAG=$1
echo "Going to tag docker containter with tag: $TAG "
docker build -f Dockerfile -t arokiagetz/k8s-web-server:v$TAG .
docker push arokiagetz/k8s-web-server:v$TAG
echo "Pushed Docker Image to arokiagetz/k8s-web-server:v$TAG"

